### ISSUE TITLE
Unable to get category names after refresh or logut and  login 

### ISSUE THREAD

**Issue by Jabiulla24** [janastu/iihs_curation_dashboard#117]
Feed is created by using add content and pasting the xml url and adding new feed after first time created the feed name is displayed .

When the user logout and login  or  refresh the application the Feeds category name is not displaying in Sidemenu bar under Feed menu.

**Comment by vaishnavisv** [comment]
The issue is with Enabling CORS refer issue #12 in iihs_couch_services
