### ISSUE TITLE
feeds not being displayed

### ISSUE THREAD

**Issue by salus-sage** [janastu/iihs_curation_dashboard#126]
debug:
I see that to display feed the app is dependent on mmfeeds.test.openrun 
while it should actually not depend, but pull from couchdb
the below piece is blocking
https://github.com/janastu/iihs_curation_dashboard/blob/master/src/app/services/feed-service.ts
```
return new Promise(resolve => {
	    var newsrack = this.settings.feedparserUrl+'/first?id='+url;
	    //console.log(newsrack);
	    this.http.get(newsrack).subscribe((response)=> {
	  //  console.log(response.json())
		this.feedNewsrack = response.json();
    
		resolve(this.feedNewsrack[0].meta);	
	   	});
	 });
```

**Comment by vaishnavisv** [comment]
Feeds are displaying from the database itself and is not  dependent on mmfeeds.test.openrun.net

The latest feeds are fetched according to category using this piece of code

getlatestfeeds(category){
	   var d = new Date();
	  var date = d.getTime();
	  console.log(category)
	return new Promise(resolve => {
	    this.db.query('feeds/latestoldestcategory', {
	      startkey: [category],
	      endkey: [category, {}],
	      limit:25
	    }).then(function (result) {
	   		console.log("res",result);
	    	resolve(result.rows);
	  	}).catch(function (err) {
	    console.log(err);
	  	});
	});
  }

**Comment by salus-sage** [comment]
What about get feeds?

**Comment by vaishnavisv** [comment]
getAllfeeds is to get the json feeds from newsrack and display the metadata to click and follow

**Comment by vaishnavisv** [comment]
After refactor this issue has been resolved .So closing this issue
