### ISSUE TITLE
website is not responsive

### ISSUE THREAD

**Issue by mkpages** [janastu/iihs_curation_dashboard#146]
website is not responding for pixel aspect ratio
![screenshot 35](https://user-images.githubusercontent.com/36531321/36303038-aeff0056-1330-11e8-87dc-d837f87bf9e5.png)

**Comment by Madhuvanthi-A** [comment]
For which screen resolution?

**Comment by manikantanva** [comment]
Screen resolution 320x560, 1024x746,768x560 and 375x560
