### ISSUE TITLE
Images not showing

### ISSUE THREAD

**Issue by mkpages** [janastu/iihs_curation_dashboard#157]
![screenshot 39](https://user-images.githubusercontent.com/36531321/36381211-e7bf1922-15aa-11e8-9114-7af2cefc35d9.png)

Why images not showing?

**Comment by vaishnavisv** [comment]
The images here are not showing because there is no image for that feed so the default placeholder is displaying

**Comment by keerthi-26** [comment]
This should be the same for modal pages as well. If images are not available in the story, the blank placeholder should not show

**Comment by vaishnavisv** [comment]
This issue is resolved and closed #234
