### ISSUE TITLE
Refresh button when pressed, new feeds related to that particular feeds must be updated automatically

### ISSUE THREAD

**Issue by pratiksha6656** [janastu/iihs_curation_dashboard#162]
When refresh button is pressed from any category the recent feeds irrespective of category are getting displayed

**Comment by vaishnavisv** [comment]
On refresh the new feeds in the database is pulled now .Everytime when the user navigates to dashboard page the feeds are pulled from newsrack other other sources are updated .So closing this issue for now

**Comment by salus-sage** [comment]
I din understand, I guess it's a valid issue, when I press refresh feed in
water category, only that category Shud update

**Comment by vaishnavisv** [comment]
To update new feeds of the category , we need to call feedparser service again,which we are anyway updating in the dashboard page.

**Comment by vaishnavisv** [comment]
Now On refresh I am calling the same API to pull feeds from database on category.
