### ISSUE TITLE
All feeds in all sections must be displayed in descending order as per the date except for boards

### ISSUE THREAD

**Issue by pratiksha6656** [janastu/iihs_curation_dashboard#167]

**Comment by vaishnavisv** [comment]
How should the boards be sorted ??

**Comment by vaishnavisv** [comment]
Sorted all sections according to date and in boards it is randomly sorted .How to sort boards

**Comment by salus-sage** [comment]
All sections Shud have default sorting by date descending. Then user can
have other choices.

**Comment by vaishnavisv** [comment]
Ya now it is like that only.But I did not understand what pratiksha meant
