### ISSUE TITLE
Header alignment is not proper when dropdown button is clicked

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/iihs_curation_dashboard#171]
![small_screen](https://user-images.githubusercontent.com/21305673/36408536-f7ea3378-162b-11e8-9e1d-ae027929a3ba.png)

**Comment by pratiksha6656** [comment]
Do the following changes in header-component.css to solve the issue:

@media only screen and (min-width: 1024px)
<style>…</style>
.menu-item[_ngcontent-c2] {
    position: absolute;
    top: 40px;
}
Do this for all screen size
