### ISSUE TITLE
if user not part of any group,functionality of boards and annotations

### ISSUE THREAD

**Issue by vaishnavisv** [janastu/iihs_curation_dashboard#202]
For the user who is not part of any group,how to implement his boards.As we have discussed that boards is for groups.

**Comment by salus-sage** [comment]
Hi thought v ll have a default group which any stray user ll be part of?

**Comment by vaishnavisv** [comment]
And this default group will be created by us in the database???

**Comment by salus-sage** [comment]
Us means super admin,

**Comment by vaishnavisv** [comment]
Ya Super admin.Now we are by default making a iihs member as admin and the same way I need to create a default group and that admin will be part of that group and also can create his/her group
