### ISSUE TITLE
IIHS Curation board

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#218]
The feeds are not pulling in news after 16th March. Also the loading time as discussed in the meeting is quite a long till now.

**Comment by vaishnavisv** [comment]
Can you give more details on channel name that was not pulled after 16th march ??
As I can get feeds till 12th April for channel AMRUT Smart Cities Mission

**Comment by vaishnavisv** [comment]
Can you update me as soon as possible on this issue.
Till date I am able to pull new feeds for the channel

**Comment by vaishnavisv** [comment]
Resolved hence closing

**Comment by salus-sage** [comment]
Is the chron job updating all categories dynamically? Or still u got the
category hardcoded?

**Comment by vaishnavisv** [comment]
Updating all categories dynamically
