### ISSUE TITLE
Share Button Alignment

### ISSUE THREAD

**Issue by keerthi-26** [janastu/iihs_curation_dashboard#226]
![issue 225](https://user-images.githubusercontent.com/36663187/38987673-40a184c8-43ee-11e8-8179-9fc5a8bf6843.JPG)

Font and commands not aligned in the sharing pop up box. It opening in an odd place as well. Move and align this.

**Comment by vaishnavisv** [comment]
Will this view be better??
![screenshot from 2018-04-19 17 58 04](https://user-images.githubusercontent.com/24469787/38991432-67b7411c-43fb-11e8-99de-d0d7f67d0d21.png)

**Comment by keerthi-26** [comment]
Yes, this is much better. On top include the words "Boards to Share" or something to indicate what is to be done at this icon

**Comment by vaishnavisv** [comment]
Ok I will give it to the button title which will look like dis
![screenshot from 2018-04-19 18 17 14](https://user-images.githubusercontent.com/24469787/38992371-2acedb40-43fe-11e8-8726-6ba6af639c50.png)
