### ISSUE TITLE
Navigating back to archive after publishing

### ISSUE THREAD

**Issue by keerthi-26** [janastu/iihs_curation_dashboard#229]
In the curation platform, there is no way for the curator to go back and see the archive link after publishing a board to archive

**Comment by salus-sage** [comment]
The in here, are is two fold, we call roles.
So for role user, who doesn't sign in or register, is public access,
published page is for public, and user who reach that page need not get to
the dashboard.

Th second sort is the curator, who publishes the page and should already
know how to go to dashboard.

We should do a interaction rating for this app. For that we need the user
flow diagram.
