### ISSUE TITLE
Not able to publish and share stories from boards

### ISSUE THREAD

**Issue by keerthi-26** [janastu/iihs_curation_dashboard#232]
Not able to publish and get archive URL even after trying many times. 
<img width="957" alt="archive issue" src="https://user-images.githubusercontent.com/36663187/39125214-d88f1b30-471b-11e8-9faf-47bdd047e669.png">

**Comment by vaishnavisv** [comment]
I have resolved the issue and pulled to the server .Verify it once .

**Comment by keerthi-26** [comment]
Issue still persists. 
<img width="947" alt="archive issue 1" src="https://user-images.githubusercontent.com/36663187/39252840-26c38206-48c4-11e8-912a-a6527e1c4e82.png">

**Comment by vaishnavisv** [comment]
I just now added few feeds to the  board Infra power energy and published and it is published.
![screenshot from 2018-04-26 09 26 34](https://user-images.githubusercontent.com/24469787/39285105-3e62485a-4934-11e8-8920-ef179a9a8d58.png)
