### ISSUE TITLE
Remove image thumbnails in archive

### ISSUE THREAD

**Issue by keerthi-26** [janastu/iihs_curation_dashboard#240]
Please remove blank image placeholders for stories that don't have a thumbnail image to display in the archive.

<img width="960" alt="archive image" src="https://user-images.githubusercontent.com/36663187/39305186-d3a2e79a-4979-11e8-8617-59863e4c8473.png">

**Comment by vaishnavisv** [comment]
For Media monitor view its not fixed yet
