### ISSUE TITLE
No feeds after browser refresh.

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/iihs_curation_dashboard#246]
Error:Failed to load resource: the server responded with a status of 409 (Conflict)

![no_feeds](https://user-images.githubusercontent.com/21305673/39325315-7deac8fa-49af-11e8-9863-f1e693851a23.png)

**Comment by Jabiulla24** [comment]
after debugging the issue i observed when we click on sub menu, the returned value  from the api is null when it is  assigned to the rendering variable.
