### ISSUE TITLE
Feeds are not displayed if user navigate from sidebar.

### ISSUE THREAD

**Issue by Madhuvanthi-A** [janastu/iihs_curation_dashboard#247]
1. Failed to load resource: the server responded with a status of 504 (Gateway Time-out)
/#/feeds?feedname=OpenNGO&subcategory=OpenNGO:1 

2. Failed to load http://mmfeeds.test.openrun.net/?user=null: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://mmclient.test.openrun.net' is therefore not allowed access. The response had HTTP status code 504.

**Comment by vaishnavisv** [comment]
We are resolving this issue currently and update you in some time and you can test again
