### ISSUE TITLE
Content overlapping

### ISSUE THREAD

**Issue by keerthi-26** [janastu/iihs_curation_dashboard#249]
We should have already resolved such issues of overlapping and alignment. This is happening in boards with many stories. 
![boards](https://user-images.githubusercontent.com/36663187/39409191-4d593b88-4c00-11e8-95dd-09231dfb6e88.JPG)

**Comment by keerthi-26** [comment]
Happening in other places too 
![overlap](https://user-images.githubusercontent.com/36663187/39409301-333e3b02-4c02-11e8-8b52-041d6deae696.JPG)

**Comment by vaishnavisv** [comment]
The content overlapping is solved 
![screenshot from 2018-04-30 10 20 07](https://user-images.githubusercontent.com/24469787/39415387-541833f6-4c60-11e8-80ab-28c3ef173f18.png)

**Comment by salus-sage** [comment]
What's the update on this issue?
