### ISSUE TITLE
As suggested I tried refreshing the feeds. Not working upto date

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#254]
The latest feeds are showing now till 4 May. I have to click the refresh button more than 5 6 times to get to 4 May. Some of the categories are showing till 7 May. Do I need to do it always like this?. As technically if I am refreshing the feeds today it should show till 9 May. We would ideally want it to auto refresh.

**Comment by vaishnavisv** [comment]
Resolved hence closing
