### ISSUE TITLE
Slow Loading Problem

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#255]
The interface is taking a long time to load , which is hindering the testing process. For eg- I published a board, which appeared in the archives page as 2018-05-09. 

When I click on it, sometimes it shows the loading sign, and the published boards do not drop down. It continues to load for more than 5 minutes, as a result I am not able to test beyond this and see what  the final Media Monitor looks like. 

Other times, when I click on the date, it gives the dropdown of published boards. When this happens, the individual boards are loading fine.

**Comment by IIHS-Comm** [comment]
This is also happening to feeds, where it just takes very long time to load.

**Comment by vaishnavisv** [comment]
The media monitor is the published view which you get on clicking publish.The media monitor will look like this.
![screenshot from 2018-05-10 09 23 27](https://user-images.githubusercontent.com/24469787/39851425-5578dada-5434-11e8-9a79-b9701313a671.png)

In this page you can copy the whole content and paste it in your mail , the content which you have pasted can be edited in the mail and sent out as media monitor. 
The archives link will take you to all the feeds published date

**Comment by vaishnavisv** [comment]
When there is long time in loading,could you be able to send the screenshot of browser's console.
To take screenshot of browser's console,press Ctrl+shift+i and you will get a tab at bottom or in the side bar . For ex: My console looks like this.
![screenshot from 2018-05-10 09 43 05](https://user-images.githubusercontent.com/24469787/39851825-d404c614-5436-11e8-8f04-5ab9a54808d4.png)

**Comment by IIHS-Comm** [comment]
Here is the screenshot of the browser console when we're trying to load Urban Agriculture. @vaishnavisv 

![agriculture_loading_consoleview](https://user-images.githubusercontent.com/38202501/39912205-9bd37eb2-551b-11e8-86c0-ddc250d9ace7.JPG)

**Comment by vaishnavisv** [comment]
Resolved hence closing
