### ISSUE TITLE
The feeds are still taking a long time to load. For e.g- Today Urban Agriculture and Urban Health took around 10-15 min to load and show the feeds.

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#269]

**Comment by salus-sage** [comment]
1. Did you use this url http://stage-client.test.openrun.net?
   2. i added Urban Health, while i couldn't find Urban Agriculture.and the
   load speed for me was 8ms

**Comment by IIHS-Comm** [comment]
Some of the feeds still taking around 10 min to load. While the testing that we were doing yesterday (21/05/18), Urban Heritage took around 10 min. I reloaded the whole website twice, but the same thing was happening.

**Comment by vaishnavisv** [comment]
Resolved hence closing
