### ISSUE TITLE
In the Archives page, though there is an option at the bottom to view Page 2, that button is not working and the current page loads again. For e.g. If we’re on page 1 and click on “next”, it re-loads page 1. 

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#271]

**Comment by salus-sage** [comment]
Archives page will not have that button, because all feeds will be
displayed as a scroll.
We aren't able to group the feeds and the paginate view together.
it's a either page 1, page 2 or Grouped by Feed name.

**Comment by salus-sage** [comment]
This issue is resolved, we have removed the unwanted button
