### ISSUE TITLE
In the Archived view, the published boards are not showing up individually.

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#272]
We are able to see the published feeds if we click on a particular date. But when we click on individual boards, there are no published feeds showing up. For e.g. in the image, we had clicked on AMRUT, and this is what we see. We also waited for a while to see if it was just being slow, but that is not the case. 
![individual feed not showing](https://user-images.githubusercontent.com/38202501/40239512-e55a4c38-5ad3-11e8-896c-43e4d150a5cc.JPG)

**Comment by salus-sage** [comment]
@vaishnavi, i can see console log of the data, but the view is not
rendering.
anything wrong in templates?
