### ISSUE TITLE
Just after publishing a board, we are getting a blank page, with the Archive link at the right hand corner. 

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#273]
After the blank page comes up, I have to click the back button every time to get back to publishing the boards, which is disrupting the workflow. Ideally, we should automatically be redirected to the boards, where we can continue publishing the rest of the boards.
On a similar note, is it possible to get all the boards to publish at once? Can we just select multiple boards and publish?

**Comment by salus-sage** [comment]
Right now with the options implemented, you should be able to
publish one board or all boards.

in case if you want to publish all boards,
you have to go to ex,
http://stage-client.test.openrun.net/#/mm/*/2018-05-18/archives
the above link has all categories, then you click on send email.
Then CTRL-A, CTRL-C, CTRL-V

But publishing is one category at a time.

is this what you are asking?

**Comment by vaishnavisv** [comment]
@salus-sage , there was a issue in displaying the feeds for the link with board name instead of *
ex:[http://stage-client.test.openrun.net/#/mm/Urban%20Agriculture/2018-05-18]
But now its resolved.
