### ISSUE TITLE
Style and formatting of publish page - 

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#276]
## After publishing all the posts, in the “send mail’ view page, is it possible to add a gap of two spaces between the heading of one category and the last line of the previous category.

 For eg, considering Urban Economic Growth & Development is a category, it will be better if we can have a two space gap before it and the last line of the previous category. Refer to the image attached and the highlighted area in it.
![mm- gap between headings](https://user-images.githubusercontent.com/38202501/40344707-a6e05884-5db3-11e8-8a2f-4c3d65d5dca5.JPG)

**Comment by vaishnavisv** [comment]
It is possible to give gap of two space between the headings.
