### ISSUE TITLE
Sort publish page and archives in Alphabetic order of categories

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#277]
## As another bug, after publishing all the categories, we are not getting a similar order of categories everytime. 
Sometimes the full published MM in “send mail’ view starts with Urban Agriculture, sometimes with AMRUT or Urban Environment. Is there a way in which we can get the published items in the order we publish it or some other way, but it should remain the same everyday. Or is there a way in which we can create a pattern for the order to remain constant?

**Comment by salus-sage** [comment]
We currently lined up a fix to sort category by alphabetical order, will
let u know when we make the changes live on server.
