### ISSUE TITLE
 Sometimes the feeds are repetitive.

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#282]
Sometimes repeating once, and other times twice or more than that. For eg. In one category the whole page has only one news item. Could this be a bug in the Curation Board, or in the News Rack feed configuration itself? Attached are two patterns of repetition for your reference.
![repetition pattern1](https://user-images.githubusercontent.com/38202501/40427933-ae82be24-5ebc-11e8-8a96-fa10a866f28f.JPG)
![repetition pattern2](https://user-images.githubusercontent.com/38202501/40427934-aeb6d286-5ebc-11e8-9865-13c70d517e6a.JPG)

**Comment by vaishnavisv** [comment]
Resolved hence closing
