### ISSUE TITLE
Redirecting and Confirmation issue after publishing a particular category.

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#283]
Is it possible to have a heading for the category in the publishing step in the place of what currently shows as “Confirm Publish”. Also, it will be very helpful if we can get some confirmation when a category has been published immediately in that page itself. At present it is very difficult to understand  whether the category is published or not finally, and this is leading to publishing one category more than once. The attached screenshot shows what the page looks like after we have hit the Publish button once. This is confusing, since it just looks like maybe nothing happened. Currently the only way we know a board has been published, is to either refresh the Archive page in a separate window, or refreshing the page after we hit Publish. There should be some way of knowing the published status without having to do either of these two. 
![post publish issue](https://user-images.githubusercontent.com/38202501/40427959-caa5724a-5ebc-11e8-87ad-73dce72790fd.JPG)

**Comment by vaishnavisv** [comment]
- [ ] Rename Confirm Publish to Category name

- [ ] Notify the feeds published for the category
