### ISSUE TITLE
Not able to delete saved feeds from 22-25 May under the Urban Climate

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#284]
![capture](https://user-images.githubusercontent.com/38202501/40701221-c288dd52-63fa-11e8-8a89-e258366567e6.JPG)

**Comment by vaishnavisv** [comment]
I just checked there is some issue with deleting.Will resolve it soon

**Comment by vaishnavisv** [comment]
The feeds deleted by one user was not reflected to other users in the board .Hence the already deleted feed was displaying and deleting already deleted feed was causing the conflict.But now I have resolved this issue .So closing the issue
