### ISSUE TITLE
Request to change the date format

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#285]
Is it possible to change the date format from the present mm-dd, yy to the UK format i.e dd-mm-yy. Kindly refer to image for the type of change needed
![change of date format](https://user-images.githubusercontent.com/38202501/40713980-f9891e2e-641e-11e8-812c-40aea51724d3.JPG)

**Comment by vaishnavisv** [comment]
Date format modified.So closing the issue
