### ISSUE TITLE
Boards added by different people are not only restricted to them, but can be viewed and published by either of them

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#286]
Recently, IIHS Chennai team also started to use the Curation Board for making their Media Monitor, which is different from the IIHS Bangalore MM. The issue is all the boards created by them is visible to us and we are able to publish them as well. Same goes for the Chennai team, they are able to see and publish our boards. This is eventually creating confusion and going forwards will be risky as well when we will have various people logged in to this website. Ideally what we would want is that the boards created by one person or team should be visible and editable by that person/team only. In the attached image, the Boards starting from ‘B” is created by the Chennai team
![merging of blr and chennai boards](https://user-images.githubusercontent.com/38202501/41534474-4ff71246-731c-11e8-9c1c-9bf70c24df6e.png)
 but is reflecting in my pre-publishing as well as publishing stage.

**Comment by salus-sage** [comment]
Hi,
Did you create a new group for blore team yet or are you still working in
default group?

**Comment by vaishnavisv** [comment]
Resolved hence closing
