### ISSUE TITLE
Difficulty in deleting saved feeds inside a particular board

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#287]
![deleting feeds within the board issue](https://user-images.githubusercontent.com/38202501/44015455-aba8d428-9eee-11e8-8653-bfb76247c28f.png)

**Comment by salus-sage** [comment]
Difficulty means? Is it getting deleted or not? More details please..

**Comment by IIHS-Comm** [comment]
We generally prefer deleting the saved feeds in a board every day before curating a fresh MM. In that process, sometimes the feeds get deleted properly and sometimes for some boards it won't.

Today (13 Aug 2018), the same problem was happening and I had a word with Vaishnavi and she suggested me to send the screenshot of the console. I would do that when the issue comes up next time. I hope that helps you to fix the bug.

**Comment by vaishnavisv** [comment]
Resolved hence closing
