### ISSUE TITLE
Issue with loading time

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#288]
Feeds of some of the categories are taking more than 5-10 min to load. I am attaching a screenshot for Economic and Development Category
![screenshot 6](https://user-images.githubusercontent.com/38202501/44032766-c1469270-9f25-11e8-8751-cebba498070d.png)

**Comment by vaishnavisv** [comment]
This issue is a error from couchdb while querying the view for not passing the URI encoded feedname
I have resolved this issue and pulled to the server

**Comment by vaishnavisv** [comment]
Resolved hence closing
