### ISSUE TITLE
Unable to remove a news item once added to board

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#293]
I am unable to remove a news item once it has been saved to a board. For e.g. If I have saved an article to the Urban Infrastructure board and later want to remove it or shift it to Urban Transportation, the "Remove" button is not working. 
![remove button not working](https://user-images.githubusercontent.com/38202501/44846809-2496a580-ac6f-11e8-8b3c-7152c2399f0e.jpg)

**Comment by vaishnavisv** [comment]
I will look into this issue and resolve it by the end of the day.

**Comment by vaishnavisv** [comment]
Resolved hence closing
