### ISSUE TITLE
Not able to delete the saved articles at one go

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#294]
Bigger boards such as Urban Economic Growth and Development and Urban Transportation can’t be deleted at one go. When I am clicking ‘Select All’ option and the hitting delete, some of the saved articles are not getting deleted. To delete them I have to click  ‘Select All’ and ‘Delete’ again and then wait for sometime for all the articles to be deleted.
First attempt:
![deleteing issue - 1st time](https://user-images.githubusercontent.com/38202501/44982376-52435d80-af93-11e8-9861-1208a5fc6bc9.png)

Second attempt:
![deleting issue- second time](https://user-images.githubusercontent.com/38202501/44982396-64bd9700-af93-11e8-9c7e-c2e41feaae2d.png)

**Comment by vaishnavisv** [comment]
Resolved hence closing
