### ISSUE TITLE
Confirmation published articles

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#295]
Every day, I delete the articles from the previous day on each board. On Friday and today, I noticed that some of the articles (which have been published) are not labelled as ‘Published’, while others are. I have attached screenshots of this from two different boards. 

![published confirmation 1](https://user-images.githubusercontent.com/38202501/44982463-9c2c4380-af93-11e8-8ae1-6b132824ed93.png)
![published confirmation 2](https://user-images.githubusercontent.com/38202501/44982465-9c2c4380-af93-11e8-8ebc-57f0396cde0b.png)

**Comment by vaishnavisv** [comment]
Did you check if these feeds are there in the archives page

**Comment by vaishnavisv** [comment]
Resolved so closing
