### ISSUE TITLE
Remove Button is partially working

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#296]
Remove button only working in boards view and not in the feeds view. It should be working in both. 

![remove button option](https://user-images.githubusercontent.com/38202501/44982484-b108d700-af93-11e8-8cfc-8c2e2f296b9b.png)

In the above example, the particular news item is saved to ‘Urban Waste’. I want to shift it to ‘Urban Infrastructure’ and remove the ‘Urban Waste’. Although we have the ‘Remove’ button in the boards view as well, which also serves an important function, I find it easy to make this change in the feeds view itself.

**Comment by vaishnavisv** [comment]
Resolved so closing
