### ISSUE TITLE
Newsrack suddenly stopped working today

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#298]
I am attaching the screenshot of the msg that I am getting when trying to reload the Newsrack.in website

![screenshot 32](https://user-images.githubusercontent.com/38202501/46407979-41227380-c72e-11e8-9b90-1500a0dfd8b9.png)

**Comment by IIHS-Comm** [comment]
Attaching another screenshot with regard to the same issue. 

![screenshot 33](https://user-images.githubusercontent.com/38202501/46408234-1127a000-c72f-11e8-8be1-5409e052d272.png)

**Comment by salus-sage** [comment]
Newsrack is working now..

**Comment by salus-sage** [comment]
Newsrack has downtime, the maintainer usually brings it up, media monitor is not directly dependendent on newsrack to stay working. Marking wontfix
