### ISSUE TITLE
Issue of feeds not loading persists

### ISSUE THREAD

**Issue by IIHS-Comm** [janastu/iihs_curation_dashboard#299]
![screenshot 34](https://user-images.githubusercontent.com/38202501/46788797-94ad4680-cd58-11e8-9ce1-462fa585bb0a.png)
![screenshot 36](https://user-images.githubusercontent.com/38202501/46788798-94ad4680-cd58-11e8-93a3-5eef178e3c67.png)
![screenshot 35](https://user-images.githubusercontent.com/38202501/46788800-94ad4680-cd58-11e8-9a64-15263c071955.png)

**Comment by salus-sage** [comment]
This issue is fixed, please re-open this if the issue persists.
