### ISSUE TITLE
For registration Response to preflight request doesn't pass access control check for user registration

### ISSUE THREAD

**Issue by Jabiulla24** [janastu/iihs_curation_dashboard#97]
Response to preflight request doesn't pass access control check: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://192.168.99.100' is therefore not allowed access after enabling cors .

**Comment by salus-sage** [comment]
The solution for this is to enable cors on super login server. U can look
up a node cors package and use config to white list domains.

**Comment by Jabiulla24** [comment]
Ya i checkd it for node cors and solved it by following method

1) Installed cors node module for superlogin
   
    npm install cors --save

2) Used cors in index.js of superlogins as below

 var express = require('express')
var cors = require('cors')
var app = express()
 
var whitelist = ['http://192.168.99.100'']     //Ip address or domain name
var corsOptions = {
  origin: function (origin, callback) {
    if (whitelist.indexOf(origin) !== -1) {
      callback(null, true)
    } else {
      callback(new Error('Not allowed by CORS'))
    }
  }
}
 
app.get('/products/:id', cors(corsOptions), function (req, res, next) {
  res.json({msg: 'This is CORS-enabled for a whitelisted domain.'})
})
 
app.listen(80, function () {
  console.log('CORS-enabled web server listening on port 80')
})
